name: hafez_elmetoon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^14.6.0
  flutter_svg: ^2.0.15
  cupertino_icons: ^1.0.8
  numberpicker: ^2.1.2



  file_picker: ^5.0.0 # For selecting files from external storage
  path_provider: ^2.0.12 # For getting file paths
  audioplayers: ^6.1.0
  record: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/Images/



  fonts:
    - family: mtnTitle_aldahabi
      fonts:
        - asset: fonts/aldahabi.ttf