name: hafez_elmetoon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^14.6.0
  flutter_svg: ^2.0.15
  cupertino_icons: ^1.0.8
  numberpicker: ^2.1.2
  file_picker: ^8.1.7 # For selecting files from external storage
  path_provider: ^2.1.3 # For getting file paths
  audioplayers: ^6.1.0
  permission_handler: ^11.1.0
  record: ^5.0.5
  just_audio: ^0.9.38
  path: ^1.9.0
  provider: ^6.1.2
  redacted: ^1.0.12
  sqflite: ^2.3.0

  floor: ^1.5.0
  floor_annotation: ^1.5.0
  floor_generator: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.14
  floor_generator: ^1.5.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/Images/



  fonts:
    - family: mtnTitle_aldahabi
      fonts:
        - asset: fonts/aldahabi.ttf